2-create-file-structure
GSG-FC03/Covid-19-app pull request #37
Opened 2021-08-05 17:35 UTC by Rawanzaqout

2021-08-05 17:36 UTC, HebaAhmad1 submitted a review, later dismissed

2021-08-05 17:37 UTC, NadaSaleh20 approved these changes

2021-08-05 17:51 UTC, Ibrahim-Jarada requested changes

2021-08-05 17:51 UTC, Ibrahim-Jarada commented on covid vaccine tracker/covid vaccine tracker.html
> +    <link rel="stylesheet" href="./covid vaccine tracker.css">
don't use spaces in your href or src so change the file name

check this link [https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#an_aside_on_casing_and_spacing](url)

2021-08-05 18:04 UTC, AbdallahGot approved these changes

2021-08-05 19:12 UTC, AbdallahGot requested changes
now you have two folders for the same page🤔, so you should delete the useless folder (the folder called covid vaccine tracker)

2021-08-05 19:51 UTC, Ibrahim-Jarada submitted a review, later dismissed

2021-08-05 19:55 UTC, AbdallahGot submitted a review, later dismissed

2021-08-06 13:13 UTC, NadaSaleh20 submitted a review, later dismissed

2021-08-06 13:37 UTC, lina-jamal reviewed
please add a description in pull request to show us what you do, and link the pull request with the related issue.
you shouldn't add the  number of issue in pull request title as ``` 2-create-file-structure  ``` just title without number

2021-08-06 13:37 UTC, lina-jamal commented on advice/advice.html
> +    <title>Document</title>
add a descriptive title for every page.

2021-08-06 14:40 UTC, HebaAhmad1 approved these changes

2021-08-06 14:44 UTC, NadaSaleh20 approved these changes

2021-08-06 14:45 UTC, MontherIsmail approved these changes

2021-08-06 14:51 UTC, Ibrahim-Jarada approved these changes

2021-08-06 15:17 UTC, merged