24 create contact css
GSG-FC03/Covid-19-app pull request #42
Opened 2021-08-06 18:29 UTC by HebaAhmad1

relates #24

2021-08-06 19:39 UTC, AbdallahGot requested changes
and don't leave many empty lines in your code

2021-08-06 19:39 UTC, AbdallahGot commented on contact/contact.css
> +    margin-top: 5px;
you can write one line here instead of three lines too.

2021-08-06 19:39 UTC, AbdallahGot commented on contact/contact.css
> +    /* margin-right: 20px; */
delete this comment

2021-08-06 19:39 UTC, AbdallahGot commented on contact/contact.css
> +    margin-left: 10px;
you can write one line here instead of three lines.
like that `margin: 47px 0 57px 10px`

2021-08-06 20:41 UTC, NadaSaleh20 approved these changes

2021-08-06 22:03 UTC, AbdallahGot approved these changes

2021-08-07 17:53 UTC, Rawanzaqout approved these changes

2021-08-07 19:01 UTC, AbdallahGot approved these changes

2021-08-07 19:01 UTC, Ibrahim-Jarada approved these changes

2021-08-07 19:02 UTC, NadaSaleh20 approved these changes

2021-08-07 19:09 UTC, Rawanzaqout approved these changes

2021-08-07 19:09 UTC, merged