create symptoms CSS
GSG-FC03/Covid-19-app pull request #47
Opened 2021-08-06 20:38 UTC by NadaSaleh20

- Making Style to the header
- Making Style to section 
- Relates #28

2021-08-08 18:14 UTC, HebaAhmad1 approved these changes

2021-08-08 18:48 UTC, Ibrahim-Jarada commented on symptoms/symptoms.js
> +var icon = document.getElementById("icon");
Try to avoid using var as you can, its preferable to use const here instead of var

2021-08-08 18:48 UTC, Ibrahim-Jarada commented on symptoms/symptoms.html
> +  <div id="button"><button class="btn next">Next</button> </div>
recommend to use meaningful and related id, I suggest to use "next-btn"

2021-08-08 18:48 UTC, Ibrahim-Jarada commented on symptoms/symptoms.js
> +document.getElementById("button").onclick = function () {
Why didn't you assign your element to a const with meaningful name like icon?
if you may use your element in your code in future just assign it to const at the top of the code

2021-08-08 18:48 UTC, Ibrahim-Jarada commented on symptoms/symptoms.js
> +document.getElementById("back").onclick = function () {
Same as the above comment

2021-08-08 19:21 UTC, AbdallahGot requested changes
![image](https://user-images.githubusercontent.com/76267220/128642861-21e0b0e6-8b2d-459f-9853-b36605e86fd3.png)
why its look like that !!!
try to avoid the horizontal scroll here.
to solve this you should use the percentage instead of using pixel in your style.
for example when we use this size of the phone its look like that 👇👇
![image](https://user-images.githubusercontent.com/76267220/128643168-c803c349-59ca-4b15-a005-fb50e5a5c5ad.png)
so using the percentage will help you, especially in responsive design.

2021-08-08 22:30 UTC, Rawanzaqout approved these changes

2021-08-09 05:31 UTC, Ibrahim-Jarada approved these changes

2021-08-09 07:05 UTC, HebaAhmad1 approved these changes

2021-08-09 07:47 UTC, MontherIsmail approved these changes

2021-08-09 08:09 UTC, lina-jamal approved these changes

2021-08-09 08:09 UTC, merged