upload images and html file
GSG-FC03/Covid-19-app pull request #49
Opened 2021-08-06 21:19 UTC by MontherIsmail

Relates #19
In this page ...

1. making header for the advice page .
2. making sections contains advices.
3. making "next" button  to move to the next page.

2021-08-08 18:14 UTC, HebaAhmad1 submitted a review, later dismissed

2021-08-08 20:45 UTC, AbdallahGot requested changes

2021-08-08 20:45 UTC, AbdallahGot commented on advice/advice.html
> +    </section>
forgot to call your js file here

2021-08-08 20:52 UTC, NadaSaleh20 approved these changes

2021-08-08 21:34 UTC, Rawanzaqout submitted a review, later dismissed

2021-08-09 07:42 UTC, Rawanzaqout approved these changes

2021-08-09 08:10 UTC, Ibrahim-Jarada reviewed
Use Prettier - Code formatter in the last commit before you push the branch
Keyboard Shortcut => Format Document : Shift+Alt+F

2021-08-09 08:10 UTC, Ibrahim-Jarada commented on advice/advice.html
> +    <link rel="stylesheet" href="../advice/advice.css">
you are in the same folder the line below would be enough
`<link rel="stylesheet" href="../advice/advice.css">`

check this link [https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#file_paths](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#file_paths)

2021-08-09 09:09 UTC, Rawanzaqout approved these changes

2021-08-09 09:14 UTC, lina-jamal approved these changes

2021-08-09 09:15 UTC, merged