Creat advice css
GSG-FC03/Covid-19-app pull request #50
Opened 2021-08-06 21:39 UTC by MontherIsmail

Relates #20 
Making style of header, sections and next button

2021-08-08 20:51 UTC, AbdallahGot requested changes
![image](https://user-images.githubusercontent.com/76267220/128645272-2263d0e8-0f71-4577-8d9e-784b35cf3129.png)

try to improve these parts style.

2021-08-09 08:24 UTC, Ibrahim-Jarada commented on advice/advice.css
> +    /*justify-content: space-between;*/
Remove the comment code line

2021-08-09 08:24 UTC, Ibrahim-Jarada commented on advice/advice.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
Remove one line from the repeated ones

2021-08-09 08:24 UTC, Ibrahim-Jarada commented on advice/advice.html
> +    <title>Document</title>
Are you sure that's the right title?

2021-08-09 08:24 UTC, Ibrahim-Jarada commented on advice/advice.js
> +        var icon = document.getElementById("icon");
Try to avoid using var as you can, its preferable to use const here instead of var

2021-08-09 10:28 UTC, MontherIsmail commented on advice/advice.html
> +    <title>Document</title>
Done

2021-08-09 11:05 UTC, NadaSaleh20 submitted a review, later dismissed

2021-08-09 15:01 UTC, NadaSaleh20 approved these changes

2021-08-09 15:06 UTC, Rawanzaqout approved these changes

2021-08-09 17:31 UTC, Ibrahim-Jarada requested changes
Be careful! when you solve conflicts!

2021-08-09 17:31 UTC, Ibrahim-Jarada commented on advice/advice.html
> +                <img src="../images/01.png" class="img-adv">
Why you changed the folder from assets to images? Are you sure that you have images folder in your branch?
Are you sure that you solved the conflict in a right way?

2021-08-09 17:31 UTC, Ibrahim-Jarada commented on advice/advice.html
> +                <img src="../images/02.png" class="img-adv">
Same as above

2021-08-09 17:31 UTC, Ibrahim-Jarada commented on advice/advice.html
> +                <img src="../images/03.png" class="img-adv">
Same as above

2021-08-09 17:31 UTC, Ibrahim-Jarada commented on advice/advice.html
> +                <img src="../images/04.png" class="img-adv">
Same as above

2021-08-09 17:31 UTC, Ibrahim-Jarada commented on advice/advice.html
> +                <img src="../images/05.png" class="img-adv">
Same as above

2021-08-09 17:31 UTC, Ibrahim-Jarada commented on advice/advice.html
> +                <img src="../images/06.png" class="img-adv">
Same as above

2021-08-09 19:04 UTC, AbdallahGot approved these changes

2021-08-09 21:28 UTC, lina-jamal approved these changes

2021-08-09 21:29 UTC, merged

2021-08-10 11:36 UTC, MontherIsmail commented on advice/advice.html
> +                <img src="../images/06.png" class="img-adv">
Done