add read me file
GSG-FC03/Covid-19-app pull request #54
Opened 2021-08-08 18:54 UTC by Rawanzaqout

relates #3

- [ ] add read me file  it contains :

- Problem
- Solution
- links
  1. design link
  2. live link
 
- User Journey
- User story
- The way of installation to run project locally
- Resources
- Team Members

2021-08-09 05:42 UTC, Ibrahim-Jarada submitted a review, later dismissed

2021-08-09 07:45 UTC, MontherIsmail submitted a review, later dismissed

2021-08-09 11:04 UTC, NadaSaleh20 approved these changes

2021-08-09 19:00 UTC, AbdallahGot requested changes

2021-08-09 19:00 UTC, AbdallahGot commented on README.md
> +https://gsg-fc03.github.io/Covid-19-app/
Live Link
[Here](https://gsg-fc03.github.io/Covid-19-app/)

2021-08-09 19:21 UTC, HebaAhmad1 submitted a review, later dismissed

2021-08-10 12:04 UTC, AbdallahGot approved these changes

2021-08-12 10:53 UTC, NadaSaleh20 submitted a review, later dismissed

2021-08-12 17:43 UTC, Ibrahim-Jarada approved these changes

2021-08-12 17:44 UTC, merged